on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: CI/CD (Blue-Green Deployment)

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Compress files
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: zip -r deploy-$IMAGE_TAG.zip ./appspec.yml ./scripts ./index.js ./package.json

      - name: Upload S3 bucket
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws s3 cp ./deploy-$IMAGE_TAG.zip s3://${{ secrets.AWS_S3_BUCKET_NAME }}/deploy-$IMAGE_TAG.zip

      - name: Trigger CodeDeploy
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws deploy create-deployment \
          --application-name ${{ secrets.AWS_CODEDEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ secrets.AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=${{ secrets.AWS_S3_BUCKET_NAME }},bundleType=zip,key=deploy-$IMAGE_TAG.zip

